# Generated by Django 6.1 on 2026-09-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('opp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('award_floor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('award_ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('clean_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('auid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('rationale', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='researchdata.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('source', models.CharField(default='provided', max_length=50)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='researchdata.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('authors_display', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('published_in', models.CharField(blank=True, max_length=255, null=True)),
                ('total_citations', models.IntegerField(default=0)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('researchers', models.ManyToManyField(related_name='papers', to='researchdata.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('source', models.CharField(default='our_model', max_length=50)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='researchdata.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='researchdata.paper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('paper', 'keyword'), name='unique_paper_keyword')],
            },
        ),
    ]
