# Generated by Django 6.1 on 2026-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='full_announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
